name: Build Uploader

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: '0.0.1'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - run: go version
      - name: Build
        run: |
          go build main.go
          
      - name: Upload Bin
        uses: actions/upload-artifact@v2
        with:
          name: stariver
          path: main
          if-no-files-found: error
      
